import type {
  ChatMessage,
  DiplomacyRelation,
  GameState,
  Letter,
  NationProfile,
  Order,
  ResourceState,
  TimelineEvent,
  WorldEvent,
} from './types';

export const GAME_STATE_VERSION = 1;

export const playerCountry = {
  name: 'Россия',
  flag: 'russia',
};

export const initialResources: ResourceState[] = [
  { id: 'gold', label: 'Золото', value: 12540, perTurn: 1250, format: 'integer' },
  { id: 'wood', label: 'Дерево', value: 8760, perTurn: 720, format: 'integer' },
  { id: 'stone', label: 'Камень', value: 6410, perTurn: 610, format: 'integer' },
  { id: 'iron', label: 'Железо', value: 7230, perTurn: 560, format: 'integer' },
  { id: 'grain', label: 'Зерно', value: 9850, perTurn: 1100, format: 'integer' },
  { id: 'population', label: 'Население', value: 146.2, perTurn: 0.8, format: 'population' },
];

export const initialChatMessages: ChatMessage[] = [
  {
    id: 'chat-1',
    time: '12:45',
    flag: 'france',
    faction: 'Франция',
    text: 'Кто заинтересован в совместной торговле редкими ресурсами?',
  },
  {
    id: 'chat-2',
    time: '12:45',
    flag: 'turkey',
    faction: 'Турция',
    text: 'Мы открыты к переговорам по новому маршруту через Черное море.',
  },
  {
    id: 'chat-3',
    time: '12:46',
    flag: 'russia',
    faction: 'Россия',
    text: 'Нужно обсудить долгосрочные поставки железа и зерна.',
  },
  {
    id: 'chat-4',
    time: '12:47',
    flag: 'india',
    faction: 'Индия',
    text: 'Внимание всем! На наши земли совершено нападение пиратов.',
  },
  {
    id: 'chat-5',
    time: '12:47',
    flag: 'germany',
    faction: 'Германия',
    text: 'Предлагаю заключить пакт о ненападении между нашими странами.',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'trade-india',
    iconKey: 'package',
    title: 'Отправить торговый караван в Индию',
    owner: 'Торговый совет',
    target: 'Дели',
    status: 'В пути',
    statusClass: 'moving',
    due: '2 дня',
    remainingTurns: 2,
    totalTurns: 2,
    cost: { gold: 420, grain: 260 },
    reward: { gold: 1500, grain: 650 },
    diplomacyDelta: { Индия: 8 },
    completeText: 'Караван достиг Дели: казна получила прибыль, а отношения с Индией укрепились.',
  },
  {
    id: 'ukraine-border',
    iconKey: 'swords',
    title: 'Укрепить границу с Украиной',
    owner: 'Генерал армии',
    target: 'Харьков',
    status: 'В работе',
    statusClass: 'progress',
    due: '3 дня',
    remainingTurns: 3,
    totalTurns: 3,
    cost: { gold: 650, iron: 360, grain: 220 },
    reward: { iron: 180 },
    diplomacyDelta: { Украина: -4 },
    completeText: 'Граница усилена: снабжение укреплено, но напряжение с Украиной выросло.',
    riskLevel: 'medium',
  },
  {
    id: 'kuzbass-mines',
    iconKey: 'pickaxe',
    title: 'Развивать шахты в Кузбассе',
    owner: 'Совет по развитию',
    target: 'Кузбасс',
    status: 'В работе',
    statusClass: 'progress',
    due: '5 дней',
    remainingTurns: 5,
    totalTurns: 5,
    cost: { gold: 900, wood: 520, stone: 400 },
    reward: { iron: 1900, stone: 850 },
    completeText: 'Шахты Кузбасса расширены: добыча железа и камня заметно выросла.',
  },
];

export const initialTimeline: TimelineEvent[] = [
  {
    icon: '⚑',
    tone: 'blue',
    title: 'Новый торговый договор',
    text: 'Франция и Испания подписали торговый договор.',
    time: '10 мин. назад',
  },
  {
    icon: '✦',
    tone: 'red',
    title: 'Военный альянс создан',
    text: 'Германия и Швейцария создали военный альянс.',
    time: '45 мин. назад',
  },
  {
    icon: '⚔',
    tone: 'red',
    title: 'Восстание подавлено',
    text: 'В провинции Синьцзян восстание было подавлено.',
    time: '2 часа назад',
  },
  {
    icon: '♜',
    tone: 'green',
    title: 'Новый правитель',
    text: 'В Аргентине новый правитель: Король Матиас I.',
    time: '3 часа назад',
  },
  {
    icon: '◎',
    tone: 'bronze',
    title: 'Торговый путь установлен',
    text: 'Турция и Индия установили новый торговый путь.',
    time: '5 часов назад',
  },
];

export const initialLetters: Letter[] = [
  {
    id: 'letter-france-trade-123',
    tone: 'neutral',
    from: 'Франция',
    subject: 'Торговое предложение',
    time: '5 мин. назад',
    body: 'Париж предлагает открыть западный торговый канал: Франция готова покупать зерно и железо, если Россия закрепит гарантии поставок.',
    responses: [
      {
        id: 'accept-trade',
        label: 'Принять торговлю',
        summary: 'Потратить золото и зерно на миссию, усилить отношения с Францией и снизить давление.',
        tone: 'support',
        resourceDelta: { gold: -180, grain: -120 },
        diplomacyDelta: { Франция: 7 },
        nationDelta: { Франция: { economy: 2, pressure: -4, threat: -1 } },
        timelineTitle: 'Французский торговый канал принят',
        timelineText: 'Канцелярия подтвердила западный торговый канал: Франция получила гарантии поставок, отношения укрепились.',
      },
      {
        id: 'ask-guarantees',
        label: 'Запросить гарантии',
        summary: 'Осторожный ответ без крупных затрат: отношения немного растут, но сделка откладывается.',
        tone: 'neutral',
        resourceDelta: { gold: -40 },
        diplomacyDelta: { Франция: 3 },
        nationDelta: { Франция: { pressure: 1 } },
        timelineTitle: 'Франции отправлены условия',
        timelineText: 'Россия запросила гарантии поставок перед западным торговым договором.',
      },
      {
        id: 'decline-trade',
        label: 'Отложить договор',
        summary: 'Сохранить ресурсы, но Франция сочтет ответ холодным.',
        tone: 'warning',
        diplomacyDelta: { Франция: -4 },
        nationDelta: { Франция: { pressure: 4, threat: 1 } },
        timelineTitle: 'Французское предложение отложено',
        timelineText: 'Канцелярия отложила торговый договор с Францией, сохранив ресурсы ценой дипломатического охлаждения.',
      },
    ],
  },
  {
    id: 'letter-turkey-straits-123',
    tone: 'red',
    from: 'Турция',
    subject: 'Дипломатический запрос',
    time: '32 мин. назад',
    body: 'Анкара требует ясных гарантий по Черному морю. Без ответа турецкие чиновники могут закрыть часть маршрутов для российских караванов.',
    responses: [
      {
        id: 'secure-straits',
        label: 'Дать гарантии',
        summary: 'Дорого, но снижает риск на Черном море и улучшает отношения с Турцией.',
        tone: 'support',
        resourceDelta: { gold: -260, iron: -120 },
        diplomacyDelta: { Турция: 6 },
        nationDelta: { Турция: { pressure: -5, threat: -3 } },
        timelineTitle: 'Черноморские гарантии отправлены',
        timelineText: 'Россия предложила Турции гарантии безопасности маршрутов, снизив напряжение у проливов.',
      },
      {
        id: 'neutral-toll',
        label: 'Предложить пошлину',
        summary: 'Получить немного золота, но Турция усилит давление.',
        tone: 'warning',
        resourceDelta: { gold: 140 },
        diplomacyDelta: { Турция: -3 },
        nationDelta: { Турция: { pressure: 5, threat: 2 } },
        timelineTitle: 'Турции предложена пошлина',
        timelineText: 'Россия ответила на запрос Турции торговой пошлиной вместо гарантий, усилив торг вокруг проливов.',
      },
    ],
  },
  {
    id: 'letter-germany-pact-123',
    tone: 'burgundy',
    from: 'Германия',
    subject: 'Военный союз',
    time: '1 час назад',
    body: 'Берлин предлагает закрытый военный пакт: обмен железом и планами снабжения в обмен на осторожное сближение.',
    responses: [
      {
        id: 'open-pact-talks',
        label: 'Открыть переговоры',
        summary: 'Потратить железо на штабные встречи и поднять отношения с Германией.',
        tone: 'neutral',
        resourceDelta: { iron: -180, gold: -90 },
        diplomacyDelta: { Германия: 7 },
        nationDelta: { Германия: { pressure: -3, army: 1 } },
        timelineTitle: 'Германский пакт вынесен на переговоры',
        timelineText: 'Россия открыла осторожные штабные переговоры с Германией, не подписывая полноценный союз.',
      },
      {
        id: 'refuse-pact',
        label: 'Отказать',
        summary: 'Сохранить ресурсы, но Берлин станет подозрительнее.',
        tone: 'danger',
        diplomacyDelta: { Германия: -6 },
        nationDelta: { Германия: { pressure: 6, threat: 3 } },
        timelineTitle: 'Германский пакт отклонен',
        timelineText: 'Россия отказала Германии в военном пакте. Берлин усилил осторожность и давление.',
      },
    ],
  },
  {
    id: 'letter-china-border-trade-123',
    tone: 'gold',
    from: 'Китай',
    subject: 'Граница и торговля',
    time: '2 часа назад',
    body: 'Пекин предлагает совместную проверку складов и восточного караванного пути, чтобы убрать спорные пошлины.',
    responses: [
      {
        id: 'joint-inspection',
        label: 'Совместная проверка',
        summary: 'Небольшие расходы, крепкий союз и меньше давления на востоке.',
        tone: 'support',
        resourceDelta: { gold: -140 },
        diplomacyDelta: { Китай: 4 },
        nationDelta: { Китай: { pressure: -4, economy: 1 } },
        timelineTitle: 'Китайская проверка согласована',
        timelineText: 'Россия и Китай согласовали проверку восточных складов, укрепив союзную торговлю.',
      },
      {
        id: 'delay-inspection',
        label: 'Отложить',
        summary: 'Без расходов, но Пекин временно повысит контроль караванов.',
        tone: 'warning',
        diplomacyDelta: { Китай: -2 },
        nationDelta: { Китай: { pressure: 3 } },
        timelineTitle: 'Проверка с Китаем отложена',
        timelineText: 'Канцелярия отложила совместную проверку с Китаем, сохранив ресурсы ценой легкого раздражения Пекина.',
      },
    ],
  },
  {
    id: 'letter-argentina-resources-123',
    tone: 'blue',
    from: 'Аргентина',
    subject: 'Обмен ресурсами',
    time: '3 часа назад',
    body: 'Буэнос-Айрес предлагает обмен зерна на золото и просит открыть постоянный дипломатический канал.',
    responses: [
      {
        id: 'resource-exchange',
        label: 'Провести обмен',
        summary: 'Отдать зерно, получить золото и добавить Аргентину в дипломатический контур.',
        tone: 'support',
        resourceDelta: { grain: -220, gold: 360 },
        diplomacyDelta: { Аргентина: 8 },
        nationDelta: { Аргентина: { economy: 3, pressure: -2 } },
        timelineTitle: 'Обмен с Аргентиной проведен',
        timelineText: 'Россия обменяла зерно на золото и открыла новый дипломатический канал с Аргентиной.',
      },
      {
        id: 'postpone-exchange',
        label: 'Отложить обмен',
        summary: 'Ресурсы не меняются, но Аргентина будет ждать нового сигнала.',
        tone: 'neutral',
        diplomacyDelta: { Аргентина: 2 },
        nationDelta: { Аргентина: { pressure: 2 } },
        timelineTitle: 'Аргентине отправлена отсрочка',
        timelineText: 'Россия отложила обмен с Аргентиной, но сохранила канал для будущих договоренностей.',
      },
    ],
  },
];

export const initialDiplomacy: DiplomacyRelation[] = [
  { flag: 'china', name: 'Китай', status: 'Союзники', tone: 'ally', score: 165 },
  { flag: 'india', name: 'Индия', status: 'Союзники', tone: 'ally', score: 120 },
  { flag: 'france', name: 'Франция', status: 'Дружественные', tone: 'friendly', score: 75 },
  { flag: 'turkey', name: 'Турция', status: 'Нейтральные', tone: 'neutral', score: 10 },
  { flag: 'germany', name: 'Германия', status: 'Нейтральные', tone: 'neutral', score: 5 },
  { flag: 'japan', name: 'Япония', status: 'Риск конфликта', tone: 'risk', score: -25 },
  { flag: 'ukraine', name: 'Украина', status: 'Враждебные', tone: 'hostile', score: -80 },
];

export const initialNations: NationProfile[] = [
  {
    id: 'russia',
    name: 'Россия',
    flag: 'russia',
    focus: 'industry',
    economy: 74,
    army: 78,
    stability: 72,
    treasury: 82,
    grain: 76,
    relation: 200,
    threat: 22,
    pressure: 18,
    goals: ['Укрепить внутренние земли', 'Расширить торговлю с союзниками', 'Сдержать пограничные риски'],
    lastAction: 'Совет ожидает распоряжений правителя.',
  },
  {
    id: 'china',
    name: 'Китай',
    flag: 'china',
    focus: 'industry',
    economy: 86,
    army: 72,
    stability: 69,
    treasury: 88,
    grain: 74,
    relation: 165,
    threat: 34,
    pressure: 28,
    goals: ['Защитить восточную торговлю', 'Покупать железо', 'Удерживать союз с Россией'],
    lastAction: 'Пекин укрепляет караванные склады.',
  },
  {
    id: 'india',
    name: 'Индия',
    flag: 'india',
    focus: 'trade',
    economy: 78,
    army: 58,
    stability: 64,
    treasury: 71,
    grain: 88,
    relation: 120,
    threat: 30,
    pressure: 22,
    goals: ['Открыть морские пути', 'Получить защиту караванов', 'Усилить союзную торговлю'],
    lastAction: 'Дели просит защитить торговые суда.',
  },
  {
    id: 'france',
    name: 'Франция',
    flag: 'france',
    focus: 'diplomacy',
    economy: 70,
    army: 61,
    stability: 77,
    treasury: 68,
    grain: 62,
    relation: 75,
    threat: 24,
    pressure: 18,
    goals: ['Собрать западный торговый пакт', 'Получить зерно', 'Не допустить войны в Европе'],
    lastAction: 'Париж ищет новый торговый договор.',
  },
  {
    id: 'turkey',
    name: 'Турция',
    flag: 'turkey',
    focus: 'trade',
    economy: 64,
    army: 66,
    stability: 58,
    treasury: 60,
    grain: 55,
    relation: 10,
    threat: 43,
    pressure: 39,
    goals: ['Контролировать проливы', 'Открыть маршрут в Индию', 'Торговаться за военные гарантии'],
    lastAction: 'Анкара наблюдает за Черным морем.',
  },
  {
    id: 'germany',
    name: 'Германия',
    flag: 'germany',
    focus: 'industry',
    economy: 82,
    army: 70,
    stability: 73,
    treasury: 76,
    grain: 58,
    relation: 5,
    threat: 38,
    pressure: 34,
    goals: ['Заключить пакт о ненападении', 'Получить железо', 'Сдержать Францию'],
    lastAction: 'Берлин предлагает осторожный пакт.',
  },
  {
    id: 'japan',
    name: 'Япония',
    flag: 'japan',
    focus: 'military',
    economy: 73,
    army: 77,
    stability: 67,
    treasury: 66,
    grain: 49,
    relation: -25,
    threat: 58,
    pressure: 55,
    goals: ['Проверить дальневосточные рубежи', 'Получить порты', 'Ослабить влияние Китая'],
    lastAction: 'Токио усиливает флот.',
  },
  {
    id: 'ukraine',
    name: 'Украина',
    flag: 'ukraine',
    focus: 'defense',
    economy: 52,
    army: 64,
    stability: 48,
    treasury: 42,
    grain: 72,
    relation: -80,
    threat: 76,
    pressure: 70,
    goals: ['Укрепить границу', 'Искать военную поддержку', 'Сорвать российские операции'],
    lastAction: 'Киев готовит оборонительные распоряжения.',
  },
];

export const initialWorldEvents: WorldEvent[] = [
  {
    id: 'world-123-black-sea',
    turn: 123,
    actor: 'Турция',
    flag: 'turkey',
    title: 'Черноморский маршрут спорен',
    text: 'Турция готова торговаться за проход караванов через Черное море, но требует гарантий безопасности.',
    tone: 'bronze',
    impact: 'trade',
  },
  {
    id: 'world-123-border',
    turn: 123,
    actor: 'Украина',
    flag: 'ukraine',
    title: 'Пограничное напряжение растет',
    text: 'Украина усиливает рубежи и ищет внешнюю поддержку. Неосторожные военные приказы могут ухудшить положение.',
    tone: 'red',
    impact: 'threat',
  },
  {
    id: 'world-123-india',
    turn: 123,
    actor: 'Индия',
    flag: 'india',
    title: 'Индия просит охрану торговли',
    text: 'Индийские купцы готовы расширять обмен зерном и золотом, если морской путь будет защищен.',
    tone: 'green',
    impact: 'trade',
  },
];

export const initialGameState: GameState = {
  version: GAME_STATE_VERSION,
  resources: initialResources,
  orders: initialOrders,
  operationPlans: [],
  timelineEvents: initialTimeline,
  letters: initialLetters,
  diplomacy: initialDiplomacy,
  nations: initialNations,
  worldEvents: initialWorldEvents,
  worldTension: 42,
  lastTurnReport: null,
  chatMessages: initialChatMessages,
  quickActionTurns: {},
  turnNumber: 123,
  selectedCountry: null,
  nextActionId: 1000,
  lastNotice: null,
  actionStatus: { kind: 'idle', message: '' },
};
